name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'menu-minglers/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag menu-minglers:$(date +%s)
